{{- if .Values.monitoring.enabled }}
{{- if .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "algo-trading.fullname" . }}
  labels:
    {{- include "algo-trading.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "algo-trading.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
{{- end }}

{{- if .Values.monitoring.grafanaDashboards.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "algo-trading.fullname" . }}-grafana-dashboards
  labels:
    {{- include "algo-trading.labels" . | nindent 4 }}
    grafana_dashboard: "true"
data:
  trading-metrics.json: |-
    {
      "annotations": {
        "list": []
      },
      "editable": true,
      "fiscalYearStartMonth": 0,
      "graphTooltip": 0,
      "links": [],
      "liveNow": false,
      "panels": [
        {
          "datasource": {
            "type": "prometheus",
            "uid": "prometheus"
          },
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "palette-classic"
              },
              "custom": {
                "axisCenteredZero": false,
                "axisColorMode": "text",
                "axisLabel": "",
                "axisPlacement": "auto",
                "barAlignment": 0,
                "drawStyle": "line",
                "fillOpacity": 10,
                "gradientMode": "none",
                "hideFrom": {
                  "legend": false,
                  "tooltip": false,
                  "viz": false
                },
                "lineInterpolation": "linear",
                "lineWidth": 1,
                "pointSize": 5,
                "scaleDistribution": {
                  "type": "linear"
                },
                "showPoints": "never",
                "spanNulls": true,
                "stacking": {
                  "group": "A",
                  "mode": "none"
                },
                "thresholdsStyle": {
                  "mode": "off"
                }
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  }
                ]
              },
              "unit": "none"
            },
            "overrides": []
          },
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 0,
            "y": 0
          },
          "id": 1,
          "options": {
            "legend": {
              "calcs": [],
              "displayMode": "list",
              "placement": "bottom",
              "showLegend": true
            },
            "tooltip": {
              "mode": "single",
              "sort": "none"
            }
          },
          "targets": [
            {
              "datasource": {
                "type": "prometheus",
                "uid": "prometheus"
              },
              "expr": "rate(trading_orders_total[5m])",
              "refId": "A"
            }
          ],
          "title": "Order Rate",
          "type": "timeseries"
        }
      ],
      "refresh": "5s",
      "schemaVersion": 38,
      "style": "dark",
      "tags": ["trading"],
      "templating": {
        "list": []
      },
      "time": {
        "from": "now-6h",
        "to": "now"
      },
      "timepicker": {},
      "timezone": "browser",
      "title": "Trading Metrics",
      "uid": "trading-metrics",
      "version": 1,
      "weekStart": ""
    }
{{- end }}

{{- if .Values.monitoring.alerts.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "algo-trading.fullname" . }}-alerts
  labels:
    {{- include "algo-trading.labels" . | nindent 4 }}
spec:
  groups:
    - name: trading
      rules:
        - alert: HighErrorRate
          expr: sum(rate(trading_errors_total[5m])) > 0.1
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: High error rate in trading system
            description: The trading system is experiencing a high rate of errors
        - alert: OrderExecutionDelay
          expr: trading_order_execution_time_seconds > 5
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: Order execution delay detected
            description: Orders are taking longer than 5 seconds to execute
{{- end }}
{{- end }}