apiVersion: v2
name: atwz
description: AlgoTradingWithZerodha - Advanced Trading Bot
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: postgresql
    version: 12.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled